kind: PersistentVolume
apiVersion: v1
metadata:
  name: db
  labels:
    type: local
    app: db
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pv-claim
  labels:
    app: db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
