#!/bin/sh

psql() {
  kubectl exec -i svc/db -- psql "$@"
}

db="$1"
if [ "$db" = "" ]
then
  echo "Usage: bootstrap-db-with-vault DATABASE"
  return 1
fi

# Sets up roles postgres and vault

export PGUSER=vault

if ! den vault/vault kv get "secret/${db}-postgres"
then
  pass="$(den vault/genpass)"
  den vault/vault kv put secret/db-postgres "PGPASSWORD=$pass" "PGUSER=postgres"
  PGPASSWORD= kubectl exec svc/db -- psql -U postgres -c "ALTER ROLE postgres WITH ENCRYPTED PASSWORD '$pass';"
fi

if ! den vault/vault kv get "secret/${db}-vault"
then
  PGUSER=$(den vault/vault kv get -field PGUSER "secret/${db}-postgres")
  PGPASSWORD=$(den vault/vault kv get -field PGPASSWORD "secret/${db}-postgres")
  pass="$(den vault/genpass)"

  den vault/vault kv put "secret/${db}-vault" "PGPASSWORD=$pass" "PGUSER=vault"
  PGPASSWORD=$PGASSWORD psql -U "$PGUSER" \
    -c "CREATE ROLE vault WITH ENCRYPTED PASSWORD '$pass' LOGIN SUPERUSER;"
  PGPASSWORD=$PGASSWORD psql -U "$PGUSER" \
    -c "CREATE DATABASE vault;"
fi
