#!/bin/sh -e

if [ "$PGUSER" = "" ]
then
  printf "Connecting with developer role\n"
  eval "$(tools/lease developer)"
fi

if [ -t 1 ]
then
  kubectl exec -it svc/db -- env PGOPTIONS="$PGOPTIONS" psql -U "$PGUSER" "$@"
else
  kubectl exec -i svc/db -- env PGOPTIONS="$PGOPTIONS" psql -U "$PGUSER" "$@"
fi
